<?php
/*******************************************************************************
* Author Remy Lalanne
* Copyright (c) 2006,2007 Remy Lalanne
*******************************************************************************/

/* ARGUMENTS */
$action        = false;
$path          = false;
$target        = false;
$xsl           = false;

if (array_key_exists("xsl",$_POST))
	$xsl = $_POST["xsl"];
if (array_key_exists("xsl",$_GET))
	$xsl = $_GET["xsl"];

if (array_key_exists("action",$_POST))
	$action = $_POST["action"];
if (array_key_exists("action",$_GET))
	$action = $_GET["action"];

if (array_key_exists("path",$_POST))
	$path = $_POST["path"];
if (array_key_exists("path",$_GET))
	$path = $_GET["path"];

if (array_key_exists("target",$_POST))
	$target = $_POST["target"];
if (array_key_exists("target",$_GET))
	$target = $_GET["target"];

header('Content-type: application/xml');
echo '<?xml version="1.0" encoding="ISO-8859-1"?>'."\n";
echo "<!-- generated by ".$_SERVER['SCRIPT_NAME']."  -->\n";
if ($xsl)
	echo '<?xml-stylesheet type="text/xsl" href="'.$xsl.'"?>'."\n";
echo "<xml>";

	$txt = "\t<POST";
	foreach ($_POST as $k => $v)
		$txt .= " " . $k.'="'.$v.'"';
	$txt .= "/>\n";
	echo $txt;

	$txt = "\t<GET";
	foreach ($_GET as $k => $v)
		$txt .= " " . $k.'="'.$v.'"';
	$txt .= "/>\n";
	echo $txt;

	$txt = "\t<FILES";
	foreach ($_FILES as $k => $v)
		$txt .= " " . $k.'="'.$v.'"';
	$txt .= "/>\n";
	echo $txt;

	/*
	$txt = "\t<FILE";
		$txt .= ' name="'.$_FILES['file']['name'].'"';
		$txt .= ' tmp_name="'.$_FILES['file']['tmp_name'].'"';
		$txt .= ' type="'.$_FILES['file']['type'].'"';
		$txt .= ' size="'.$_FILES['file']['size'].'"';
		$txt .= ' error="'.$_FILES['file']['error'].'"';
	$txt .= "/>";
	echo $txt;
	 */

function error_code ( $code = 0, $text = "" )
{
	return '<error code="'.$code.'">'.$text."</error>\n";
}

	switch ($action){
		case "copy":
			if (!copy($path,$target)){
				echo error_code(12,"Can't copy");
			}
			else
				echo error_code(0);
			break;
		case "resize":
			include "../../Addons/FileSystem/resize.php";
			$thumb = new thumbnail($path);
			$thumb->size_auto(50);
			$thumb->show();


			break;
		default:
			$txt = error_code(10,"You must provide a valid action");
	}
	echo $txt;
	echo "</xml>";
?>

