<?php
/*******************************************************************************
 * Author Remy Lalanne
 * Copyright (c) 2005,2006,2007 Remy Lalanne
 ******************************************************************************/
session_start();
header('Content-type: text/xml');
echo '<?xml version="1.0" encoding="UTF-8"?>'."\n";

include_once "service.php"; //error_code()
include_once "App/lib.user.php";
include_once "../php/DAM.php";
include_once "../php/data_model_1.xml.php";


$err = $ERR_NOERROR;
$cmd = arg("cmd");
$ret = false;

echo "<!-- generated by ".$_SERVER['SCRIPT_NAME']."  -->\n";
echo '<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">'."\n";
echo "\t<soap:Header>\n";

$err = damas_service::init();

if ($err==$ERR_NOERROR){
	if (!$cmd)
		$err = $ERR_COMMAND;
}

if ($err==$ERR_AUTHREQUIRED && $cmd=="login")
	$err = $ERR_NOERROR;

if ($err==$ERR_NOERROR){
	switch ($cmd){
		case "login":
			$ret = login( arg("user"), arg("password") );
			if( !$ret )
				$err = $ERR_AUTH;
			else
			{
				$_SESSION['user_id'] = getUserId( arg('user') );
				//$_SESSION['user_id'] = getUserId(arg('user')) or dam::insert('dam:user', arg("user"));
				//$_SESSION['user_id'] = model::searchKey( 'username', arg('user') ) or dam::insert('dam:user', arg("user"));
				$err = $ERR_NOERROR;
			}
			break;
		case "logout":
			$ret = logout();
			if (!$ret)
				$err = $ERR_LOGOUT;
			break;
		case "checkAuthentication":
			$ret = (int)checkAuthentication();
			if (!$ret)
				$err = $ERR_AUTHREQUIRED;
			break;
		case "getUserXML":
			$ret = checkAuthenticationXML();
			break;
		default:
			$err = $ERR_COMMAND;
	}
}
echo soaplike_head($cmd,$err);
echo "\t</soap:Header>\n";
echo "\t<soap:Body>\n";
echo "\t\t<returnvalue>$ret</returnvalue>\n";
echo "\t</soap:Body>\n";
echo "</soap:Envelope>\n";
?>
