<?php
/**
 * Author Remy Lalanne
 * Copyright (c) 2005-2011 Remy Lalanne
 */
session_start();

include_once "service.php";

damas_service::init_http();
damas_service::accessGranted();

//header('Content-type: application/xml');
header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=\"export.xml\"");
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Cache-Control: no-store, no-cache, must-revalidate");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
flush();

echo '<?xml version="1.0" encoding="UTF-8"?>'."\n";

$err = $ERR_NOERROR;

echo "<!-- generated by ".$_SERVER['SCRIPT_NAME']." -->\n";
if( arg('xsl') )
	echo '<?xml-stylesheet type="text/xsl" href="' . arg('xsl') . '"?>' . "\n";

$current_depth = 0;

function tagr ($id)
{
	global $current_depth;
	$tabs = "";
	for( $j=0; $j<$current_depth+1; $j++ ) $tabs .= "\t";

	// Tags
	$query = "SELECT name FROM tag WHERE node_id='$id' ORDER BY name;";
	$result = mysql_query($query);
	while( $row = mysql_fetch_array( $result ) )
	{
		$contents .= sprintf("\n%s<tag>%s</tag>",
			$tabs,
			htmlspecialchars($row['name'],ENT_NOQUOTES)
		);
	}

	// Children and links
	$query = "SELECT id FROM node WHERE parent_id='$id' ORDER BY type;";
	$result = mysql_query($query);
	$children = array();
	while( $row = mysql_fetch_array( $result ) )
		$children[] = $row['id'];
	$query = "SELECT link.tgt_id FROM link WHERE src_id='$id';";
	$result = mysql_query($query);
	while( $row = mysql_fetch_array( $result ) )
		$children[] = $row['tgt_id'];
	if( sizeof( $children ) > 0 )
	{
		$current_depth += 1;
		for( $i=0; $i < sizeof( $children ); $i++ )
		   $contents .= tagr( $children[$i] );
		$current_depth -= 1;
	}

/*
	// Links
	$query = "SELECT link.tgt_id FROM link WHERE src_id='$id';";
	$result = mysql_query($query);
	while( $row = mysql_fetch_array( $result ) )
	{
		$contents .= sprintf("\n%s<dam:link id=\"%s\"/>",
			$tabs,
			$row['tgt_id']
		);
	}

	// Reverse Links
	$query = "SELECT link.src_id FROM link WHERE tgt_id='$id';";
	$result = mysql_query($query);
	while( $row = mysql_fetch_array( $result ) )
	{
		$contents .= sprintf( "\n%s<dam:rlink id=\"%s\"/>",
			$tabs,
			$row['src_id']
		);
	}
*/
	return tag( $id, $contents );
}

function tag ($id, $contents=false)
{
	global $current_depth;
	$tabs = "";
	for( $j=0; $j<$current_depth; $j++ ) $tabs .= "\t";
	if( $id == 0 )
	{
		$type = 'project';
	}
	else
	{
		$query = "SELECT * FROM node WHERE id='$id';";
		if( !$result = mysql_query($query) )
			return false;
		if( !mysql_num_rows($result) )
			return false;
		$row = mysql_fetch_array($result);
		$type =  $row['type'];
	}
	$txt = sprintf( "\n%s<%s",
		$tabs,
		$type );
	$query = "SELECT * FROM `key` WHERE node_id='$id' ORDER BY name;";
	$result = mysql_query($query);
	while( $row2 = mysql_fetch_array($result) )
	{
		$txt .= sprintf(' %s="%s"',
			htmlspecialchars($row2['name'],ENT_QUOTES),
			htmlspecialchars($row2['value'],ENT_QUOTES)
			);
	}
	if( $contents )
	{
		$txt .=">$contents";
		$txt .="\n";
		for( $j=0; $j < $current_depth; $j++ ) $txt .= "\t";
		$txt .= "</$type>";
		return $txt;
	}
	return $txt . "/>";
}

echo tagr( arg("id") );
?>
